config/routes.rb
PersonManagement::Application.routes.draw do

  root  "periods#index"

  resources :users do
     collection do
       get :show_user
     end
  end
  resources :logs
  resources :periods do
    collection do
      get :show_period
    end
  end

end

app/models/period.rb
class Period < ActiveRecord::Base
  has_many :grades
  has_many :users, :through => :grades
end

app/controllers/periods_controller.rb
class PeriodsController < ApplicationController

  #before_filter :authenticate_user!

  def index
    @periods = Period.order(period_name: :asc).all
    @periods.map do |f|
      #今年刚入学的学生算一年级,如果遇到什么nil, 则到数据库找原因
      f.period_name = Time.now.year - f.period_name + 1
    #  puts "xxxxxxxxxperiod_name=#{f.period_name}"
    end
  end

  def new
    @period = Period.new
  end

  def create

    #这里我还要考虑是否存在重复的问题
  #  puts "---#{period_params}---"

    #将前端数据，与后端进行对比，如果相同，则返回错误，如果不同，则存入数据库
    #两种方法：
    #1将数据和后端每个都进行对比，如果相同，则不存入。这有个问题，如果对比时前几个都不同，那么就得执行好几次if 操作。
    #
    #2将前端数据,通过where查询的方式，如果查询不到，则认为数据库中没有这条记录，则将记录存入数据库。

    @result = Period.where("period_name=?",params[:period][:period_name]).where("class_name=?",params[:period][:class_name])
  #  puts "oooooooooooooooooooooo#{@result}ooo"

    #这里的困惑  empty? 和 nil 之间的关系？  @result.empty? #true/false
    if @result.empty?
      @period = Period.create period_params
      redirect_to periods_path
    else
      redirect_to new_period_path
    end
  end

  def show
    @period = Period.find params[:id]
  end

  def edit
    @period = Period.find params[:id]
    @periods = Period.all

  end


  #update,注意事项：period的id不会变
  def update
    @period = Period.find params[:id]

    @result = Period.where.not("id = #{params[:id]}").where("period_name=?",params[:period][:period_name]).where("class_name=?",params[:period][:class_name])
   # puts "xxxxxxxxxxxx@result=#{@result.inspect}"
    if @result.empty?
   #   puts "xxxxxxxxxxxxparams[:id]= #{params[:id]}"
   #   puts "xxxxxxxxxxx@result.empty=#{@result.empty?}"
   #   puts "xxxxxxxxxxxperiod_params=#{session_params}"

    #  @period = @session.update session_params
      @period.update period_params
      redirect_to @period
    else
      #当数据库中已有数据，则返回到edit页面，重新编辑
      #在重定向的时候，传值。
      redirect_to edit_period_path(@period)
    end
  end

  def destroy
    @period = Period.find params[:id]
    @period.destroy
    redirect_to periods_path
  end

  def show_period
    puts "xxxxxxshow_period=#{params}"
    @results = Period.where("period_name = ?", params[:period_name])
  end

  private
  def period_params
    params.require(:period).permit(:period_name, :class_name, :state_id)
  end
end

app/views/periods/edit.html.erb
<h2>班级年级编辑页面</h2>

<%= form_for @period, url: period_path(@period), method: :patch, html: {id: "formid"} do |f| %>
  <p>
    <%= f.label "学生入学学年" %>
    <%= f.text_field :period_name, placeholder: "请填入数字"  %>
  </p>

  <p>
    <%= f.label "学生所在班级" %>
    <%= f.text_field :class_name, placeholder: "请填入数字" %>
  </p>

  <p>
    <%= f.label "班级状态" %>
    <%= f.collection_select(:state_id, State.where('role = 1'), :id, :state_name) %>
  </p>

  <p>
    <%= f.submit '提交'%>
  </p>

<% end %>

  <!--如果填入的信息存在重复，这里就是提示信息显示的地方-->
  <!--这里貌似无法进行@message的传递-->
  <% if @message %>
    <p>您输入的数据在数据库中已有存档，请您仔细检查</p>
  <% end %>

<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#formid').validate({
    rules:{
      "period[period_name]": {
        required: true,
        minlength:4,
        digits:true
      },
      "period[class_name]": {
        required: true,
        digits:true
      }
    }
  });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });


</script>

app/views/periods/index.html.erb
<style>
  body{
    width:200px; margin:50px auto;
  }

</style>

<p>班级资料库</p>
<p>
  <%= link_to "新增班级", new_period_path %>
</p>

<form action="/periods/show_period" method="get" >
  查找年级：
  <!--年级-->
  <input type="text" name="period_name" value="" />
  <input type="submit" value="提交" />
</form>

<% @periods.each do |f| %>
  <table class="table table-bordered" >
    <tr>
      <td>高 <%= f.period_name %> </td>
      <td> (<%= f.class_name %>)&nbsp; 班 </td>
      <td>&nbsp;&nbsp;&nbsp;<%= State.where("id = #{ f.state_id}").first.state_name %> </td>
      <td><%= link_to "查看", period_path(f)  %></td>
      <td><%= link_to "编辑", edit_period_path(f) %></td>
      <td><%= link_to "删除", period_path(f), method: :delete, data:{confirm: "您确定删除"} %></td>
    </tr>
  </table>
<% end %>

app/views/periods/new.html.erb
<h2>创建班级年级的首页</h2>
<p style="padding: 10px 0;">
  <%= link_to "返回", periods_path %>
</p>

<%= form_for @period, html: {id: "formid"} do |f| %>
  <p>
    <%= f.label "学生入学学年" %>
    <%= f.text_field :period_name, placeholder: "请填入数字"  %>
  </p>

  <p>
    <%= f.label "学生所在班级" %>
    <%= f.text_field :class_name, placeholder: "请填入数字" %>
  </p>

  <p>
    <%= f.label "班级状态" %>
    <%= f.collection_select(:state_id, State.where('role = 1'), :id, :state_name) %>
  </p>

  <p>
    <%= f.submit '提交'%>
  </p>

<% end %>

  <!--如果填入的信息存在重复，这里就是提示信息显示的地方-->
  <% if @result %>
    <p><%= @result %></p>
  <% end %>

<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#formid').validate({
    rules:{
      "period[period_name]": {
        required: true,
        minlength:4,
        digits:true
      },
      "period[class_name]": {
        required: true,
        digits:true
      }
    }
  });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });


</script>

app/views/periods/show.html.erb
<div style="width:200px; margin:50px auto;">
  <p>
    <strong>年级：</strong>
    <%= @period.period_name  %>
  </p>

  <p>
    <strong>班级：</strong>
    <%= @period.class_name  %>
  </p>

  <!--这里需要注意，找到的是数组的格式，所以，还需要从数组的格式中取到我们需要的那个数据
      还要注意 where语句需要用到  双引号。

  -->
  <p>
    <strong>班级状态：</strong>
    <%= State.where(" id = #{@period.state_id} ").first.state_name %>
  </p>

  <p>
    <%= link_to "返回", periods_path  %>
  </p>
</div>

app/views/periods/show_period.html.erb
<!--这里应该展示所有的搜到的信息-->
<table class="table table-devise">
  <tr>
    <td>第几届</td>
    <td>班级</td>
    <td>状态</td>
  </tr>
  <% if @results %>
    <% @results.each do |f| %>
      <tr>
        <td><%= f.period_name %></td>
        <td><%= f.class_name %></td>
        <td><%= f.state_id %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to "返回", periods_path %>