config/routes.rb
PersonManagement::Application.routes.draw do

  root  "periods#index"

  resources :users do
     collection do
       get :show_user
     end
  end
  resources :logs
  resources :periods do
    collection do
      get :show_period
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  #devise :database_authenticatable, :registerable,
  #       :recoverable, :rememberable, :trackable, :validatable
  has_many :grades
  has_many :periods, :through => :grades

  has_many :logs
  has_many :states, :through => :logs
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    User.create user_params
    Period.create :period_name => params[:period][:period_name], :class_name => params[:period][:class_name]
    redirect_to users_path
  end

  def show
    @user = User.find params[:id]
    @logs = Log.where("user_id = ?", params[:id])
  end

  def edit
    @user = User.find params[:id]
    @period = @user.periods
    @state = @user.states
    puts "xxxxedit@period=#{@period.inspect}x"
    puts "xxxxedit@period=#{@period.first.period_name}x"
    #puts "xxxxedit@state=#{@state}"
  end

  def update
    #puts "xxxxupdate=#{params}"
    @user = User.find params[:id]
    @period = Period.find params[:id]
    puts "xxx@user=#{@user.inspect}"
    puts "xxxupdateparams=#{params}"
    #@user.update user_params
    #@period.update :period_name => params[:period][:period_name], :class_name => params[:period][:class_name], :state_id => params[:period][:state_id]
    render :text => 'lala'
    #redirect_to users_path
  end

  def destroy
    @user = User.find params[:id]
    @user.destroy
    redirect_to users_path
  end

  def show_user
    #puts "xxxxxuser_search=#{params}"
    if params[:name] == ''
      if params[:state_name] == ''
        @results = User.all
      elsif
        @results = User.where("state_name = ?", params[:state_name])
      end
    elsif
      if params[:state_name] == ''
        @results = User.where('name = ?', params[:name])
      elsif
        @results = User.where('name = ?', params[:name]).where('state_name = ?', params[:state_name])
      end
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :sex, :age, :id_card, :role, :phone, :email, :person_number, :state_id)
  end
end

app/views/users/edit.html.erb
  <h2>修改人员</h2>
  <%= form_for @user, url: user_path(@user), method: :patch, html: {id: "formid"} do |f| %>
    <p>
      <%= f.label "名字" %>
      <%= f.text_field :name, placeholder: "请填入姓名"  %>
    </p>
    <p>
      <%= f.label "性别" %>
      <%= f.text_field :sex, placeholder: "请填入性别" %>
    </p>
    <p>
      <%= f.label "年龄" %>
      <%= f.text_field :age, placeholder: "请填入年龄" %>
    </p>
    <p>
      <%= f.label "身份证号" %>
      <%= f.text_field :id_card %>
    </p>
    <p>
      <%= f.label "手机号" %>
      <%= f.text_field :phone %>
    </p>
    <p>
      <%= f.label "邮箱" %>
      <%= f.text_field :email %>
    </p>
    <p>
      <%= f.label "借书证" %>
      <%= f.text_field :age %>
    </p>
    <p>
      角色：
      <%= select_tag "user[role]", options_for_select([ ['老师','老师'],['学生','学生']], @user.role) %>
    </p>
    <p>
      人员状态：
      <%= select_tag "user[state_id]", options_from_collection_for_select(State.where("role = 0"), :id, :state_name, @user.state_id) %>
    </p>
    <p>
    <!--
      这里的输入框居然是空的，真的难以理解。
      居然没有id值，让我很困惑
    -->
      <%= select_tag "period[period_name]", options_from_collection_for_select(Period.select(:period_name).distinct, :id, :period_name, @period.first.period_name) %>
      届
      <%= select_tag "period[class_name]", options_from_collection_for_select(Period.select(:class_name).distinct, :id, :class_name, @period.first.class_name) %>
      班
      <!--班级的state用1代替-->
      <%= select_tag "period[state_id]", options_from_collection_for_select(State.where("role = 1"), :id, :state_name, @state.first.state_name) %>
    </p>
    <p>
      <%= f.submit '提交'%>
    </p>
  <% end %>

<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#formid').validate({
    rules:{
      "user[name]": {
        required: true,
      },
      "user[sex]": {
        required: true,
      },
      "user[age]": {
        required: true,
        digits:true
      },
      "user[id_card]": {
        required: true
      },
      "user[role]": {
        required: true
      },
      "user[phone]": {
        required: true,
        digits:true
      },
      "user[email]": {
        required: true
      },
      "user[person_number]": {
        required: true,
        digits:true
      },
      "user[state_id]": {
        required: true,
        digits:true
      },
      "period[period_name]":{
        required: true
      },
      "period[class_name]":{
        required: true
      },
      "period[state_id]":{
        required: true
      }
  /*,
      "period[period_name]": {
        required: true
      },
      "period[class_name]": {
        required: true
      },
      "period[state_id]": {
        required: true
      }
      */
    }
  });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });
</script>

app/views/users/index.html.erb
<form action="/users/show_user" method="get" >
  查询：
  <!--姓名-->
  <input type="text" name="name" value="" placeholder="填写名字" />
  <input type="text" name="state_name" value="" placeholder="填写状态" />

  <input type="submit" value="提交" />
</form>

<!--新建学生按钮-->
<%= link_to "新建学生", new_user_path %>

<table class="table table-bordered" style="width:80%; margin:80px auto;">
  <tr>
    <th>姓名</th>
    <th>性别</th>
    <th>年龄</th>
    <th>身份证号</th>
    <th>角色</th>
    <th>手机号码</th>
    <th>邮箱</th>
    <th>借书证</th>
    <th>人员状态</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |f| %>
    <tr>
      <td><%= f.name %></td>
      <td><%= f.sex %></td>
      <td><%= f.age %></td>
      <td><%= f.id_card %></td>
      <td><%= f.role %></td>
      <td><%= f.phone %></td>
      <td><%= f.email  %></td>
      <td><%= f.person_number %></td>
      <td><%= f.state_id %></td>
      <td><%= link_to "查看", user_path(f) %></td>
      <td><%= link_to "编辑", edit_user_path(f) %></td>
      <td><%= link_to "删除", user_path(f), method: :delete, data:{confirm:"您确定删除!"} %></td>
      <td></td>
      <td><%= link_to "编辑记录", new_log_path(f)  %></td>
    </tr>
  <% end %>
</table>

app/views/users/new.html.erb
  <h2>新建人员</h2>

  <!--这个form应该打到create路由-->
  <form action="/users" method="post" id="formid">
    <!--authenticity-->
    <input type="hidden" name="authenticity_token" value="fslfjlsflsjflsljfworuxn" />
    <!--以下是学生的基本信息-->
    <p>
      姓名：<input type="text" name="user[name]" placeholder:"请输入姓名">
    </p>
    <p>
      性别：
      <input type="text" name="user[sex]" placeholder:"请输入姓名">
    </p>
    <p>
      年龄：
      <input type="text" name="user[age]" placeholder:"请输入姓名">
    </p>
    <p>
      身份证：
      <input type="text" name="user[id_card]" placeholder:"请输入姓名">
    </p>
    <p>
      电话：
      <input type="text" name="user[phone]" placeholder:"请输入姓名">
    </p>
    <p>
      邮箱：
      <input type="text" name="user[email]" placeholder:"请输入姓名">
    </p>
    <p>
      借书证：
      <input type="text" name="user[person_number]" placeholder:"请输入姓名">
    </p>
    <p>
      角色：
      <select name="user[role]">
        <option>老师</option>
        <option>学生</option>
      </select>
    </p>
    <p>
      人员状态：
      <%= select_tag "user[state_id]", options_from_collection_for_select(State.where("role = 0"), :id, :state_name) %>
    </p>
    <!--
      以下是学生的年级班级信息，单纯的通过options_from_collecton_for_select不能很好的将periods表中的很多字段显示，
      1我在想，如果我需要用到options_from_collection_for_select方法，那么，我应该将后端传过来的数据
      进行处理，使得在前端的页面，我能够使用options_from_collectio_for_select
      2我还得考虑，数据在前端采集完全后，传给后端的时候，我该怎么办？
      3不用options_from_collectin_for_select标识 届（年份）.

      4如果用到options_from_collection_for_select ，
      其中的逻辑是：我先去创建班级，之后，我到人员新建页面，新创建人员。
    -->
    <%= select_tag "period[period_name]", options_from_collection_for_select(Period.select(:period_name).distinct, :id, :period_name) %>
    届
    <%= select_tag "period[class_id]", options_from_collection_for_select(Period.select(:class_name).distinct, :id, :class_name) %>
    班
    <!--班级state用1代替-->
    <%= select_tag "period[state_id]", options_from_collection_for_select(State.where("role = 1"), :id, :state_name) %>
    <!--这个是提交按钮-->
    <p>
      <input type="submit" value="提交" />
    </p>
  </form>

<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#formid').validate({
    rules:{
      "user[name]": {
        required: true,
      },
      "user[sex]": {
        required: true,
      },
      "user[age]": {
        required: true,
        digits:true
      },
      "user[id_card]": {
        required: true,
      },
      "user[role]": {
        required: true,
      },
      "user[phone]": {
        required: true,
        digits:true
      },
      "user[email]": {
        required: true,
      },
      "user[person_number]": {
        required: true,
        digits:true
      },
      "user[state_id]": {
        required: true,
        digits:true
      },
      "period[period_name]": {
        required: true,
      },
      "period[class_name]": {
        required: true,
      },
      "period[state_id]": {
        required: true,
      }
    }
  });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });
</script>

app/views/users/show.html.erb
  <p>
    <strong>名字:</strong>
    <%= @user.name %>
  </p>

  <p>
    <strong>性别:</strong>
    <%= @user.sex %>
  </p>

  <p>
    <strong>年龄:</strong>
    <%= @user.age %>
  </p>

  <p>
    <strong>身份证:</strong>
    <%= @user.id_card %>
  </p>

  <p>
    <strong>角色:</strong>
    <%= @user.role %>
  </p>

  <p>
    <strong>电话:</strong>
    <%= @user.phone %>
  </p>

  <p>
    <strong>邮箱:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>借书证:</strong>
    <%= @user.person_number %>
  </p>

  <p>
    <strong>状态:</strong>
    <%= State.where("id = ?", @user.state_id).first.state_name %>
  </p>

  <!--人员所在年级班级的情况-->
  <p>
    年级：<%= @user.periods.first.period_name  %>
  </p>

  <p>
   班级： <%= @user.periods.first.class_name  %>
  </p>

  <!--log-->
  <% @logs.each do |f| %>
    <div>
      <p>开始时间：<%= f.start_date %></p>
      <p>截止时间：<%= f.end_date %></p>
    </div>
  <% end %>

  <!--返回-->
  <p>
    <%= link_to "返回", users_path  %>
  </p>

app/views/users/show_user.html.erb
<!--这里应该展示所有的搜到的信息-->
<table class="table table-devise">
  <% if @results %>
    <% @results.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.sex %></td>
        <td><%= f.age %></td>
        <td><%= f.id_card %></td>
        <td><%= f.role %></td>
        <td><%= f.phone %></td>
        <td><%= f.email %></td>
        <td><%= f.person_number %></td>
        <td><%= f.state_id %></td>
      </tr>
    <% end %>
  <% end %>
</table>

<%= link_to "返回", users_path %>

app/views/users/user_search.html.erb
<!--这里应该展示所有的搜到的信息-->
<table class="table table-devise">
  <% if @results %>
    <% @results.each do |f| %>
      <tr>
        <td><%= f.name %></td>
        <td><%= f.sex %></td>
        <td><%= f.age %></td>
        <td><%= f.id_card %></td>
        <td><%= f.role %></td>
        <td><%= f.phone %></td>
        <td><%= f.email %></td>
        <td><%= f.person_number %></td>
        <td><%= f.state_id %></td>
      </tr>
    <% end %>
  <% end %>
</table>


<%= link_to "返回", users_path %>