config/routes.rb
PersonManagement::Application.routes.draw do

  root  "periods#index"

  resources :users do
     collection do
       get :show_user
     end
  end
  resources :logs
  resources :periods do
    collection do
      get :show_period
    end
  end

end

app/models/log.rb
class Log < ActiveRecord::Base
  belongs_to :user
  belongs_to :state
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  def index
    @logs = Log.all
  end

  def new
    @log = Log.new

  end

  def create
    @log = Log.create log_params
    redirect_to @log
  end

  def show
    @log = Log.find params[:id]
  end

  def edit
    @log = Log.find params[:id]
  end

  def update
    @log = Log.find params[:id]
    @log.update log_params

    redirect_to logs_path
  end

  def destroy
    @log = Log.find params[:id]

    @log.destroy

    redirect_to logs_path
  end


  private
  def log_params
    params.require(:log).permit(:user_id, :state_id, :content, :start_date, :end_date)
  end

end

app/views/logs/edit.html.erb
<h2>新建记录</h2>

<%= form_for @log, url: log_path(@log), method: :patch, html: {id: "logid"} do |f| %>
  <p>
    <%= f.label "名字" %>
    <%= f.text_field :user_id %>
  </p>

  <p>
    <%= f.label "事件" %>
    <%= f.text_field :state_id %>
  </p>

  <p>
    <%= f.label "具体情况" %>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label "开始时间" %>
    <%= f.text_field :start_date, placeholder: "2016-11-11" %>
  </p>

  <p>
    <%= f.label "截止时间" %>
    <%= f.text_field :end_date, placeholder: "2016-11-11" %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>

<% end %>


<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#logid').validate({
    rules:{
      "log[user_id]": {
        required: true,
      },
      "log[state_id]": {
        required: true,
      },
      "log[content]": {
        required: true,
        digits:true
      },
      "log[start_date]": {
        required: true,
      },
      "log[end_date]": {
        required: true,
        }
    });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });


</script>

app/views/logs/index.html.erb
<table class="table table-devise">
  <tr>
    <th>姓名</th>
    <th>状态</th>
    <th>具体情况</th>
    <th>开始时间</th>
    <th>截止日期</th>
  </tr>
  <% @logs.each do |f| %>
    <tr>
      <td><%= f.user_id %></td>
      <td><%= f.state_id %></td>
      <td><%= f.content %></td>
      <td><%= f.start_date %></td>
      <td><%= f.end_date %></td>
      <td><%= link_to "查看", log_path(f) %></td>
      <td><%= link_to "编辑", edit_log_path(f) %></td>
      <td><%= link_to "删除", log_path(f), method: :delete, data:{confirm:"您确定删除!"} %></td>
    </tr>
  <% end %>
</table>

app/views/logs/new.html.erb
<h2>新建记录</h2>

<%= form_for @log, html: {id: "logid"} do |f| %>
  <p>
    <%= f.label "名字" %>
    <%= f.text_field :user_id %>
  </p>

  <p>
    <%= f.label "事件" %>
    <%= f.text_field :state_id %>
  </p>

  <p>
    <%= f.label "具体情况" %>
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.label "开始时间" %>
    <%= f.text_field :start_date, placeholder: "2016-11-11" %>
  </p>

  <p>
    <%= f.label "截止时间" %>
    <%= f.text_field :end_date, placeholder: "2016-11-11" %>
  </p>

  <p>
    <%= f.submit "提交" %>
  </p>

<% end %>


<script>

  //这里对form进行验证,重要的事情请重视起来，用到插件jquery.validate.js
  //然后，form内部的input框，所有的限制条件，写在rules中。
  $('#logid').validate({
    rules:{
      "log[user_id]": {
        required: true,
      },
      "log[state_id]": {
        required: true,
      },
      "log[content]": {
        required: true,
        digits:true
      },
      "log[start_date]": {
        required: true,
      },
      "log[end_date]": {
        required: true,
        }
    });

  //这是对英文注释的中文翻译
  jQuery.extend(jQuery.validator.messages, {
    required: "输入框不能为空",
    remote: "请修正该字段",
    email: "请输入正确格式的电子邮件",
    url: "请输入合法的网址",
    date: "请输入合法的日期",
    dateISO: "请输入合法的日期 (ISO).",
    number: "请输入合法的数字",
    digits: "只能输入整数",
    creditcard: "请输入合法的信用卡号",
    equalTo: "请再次输入相同的值",
    accept: "请输入拥有合法后缀名的字符串",
    maxlength: jQuery.validator.format("请输入一个 长度最多是 {0} 的数字"),
    minlength: jQuery.validator.format("请输入一个 长度最少是 {0} 的数字"),
    rangelength: jQuery.validator.format("请输入 一个长度介于 {0} 和 {1} 之间的数字"),
    range: jQuery.validator.format("请输入一个介于 {0} 和 {1} 之间的值"),
    max: jQuery.validator.format("请输入一个最大为{0} 的值"),
    min: jQuery.validator.format("请输入一个最小为{0} 的值")
  });


</script>

app/views/logs/show.html.erb
<%= link_to "返回", logs_path %>
<p>
  <strong>姓名</strong>
  <%= @log.user_id %>
</p>

<p>
  <strong>事件</strong>
  <%= @log.state_id %>
</p>

<p>
  <strong>开始时间</strong>
  <%= @log.start_date %>
</p>

<p>
  <strong>截止时间</strong>
  <%= @log.end_date %>
</p>